---
all:
  children:
    stack:
      children:
        kafka:
          hosts:
            kafka01.example.internal:
              ansible_host: 192.0.2.11
            kafka02.example.internal:
              ansible_host: 192.0.2.12
            kafka03.example.internal:
              ansible_host: 192.0.2.13
        kafka_connect:
          hosts:
            connect01.example.internal:
              ansible_host: 192.0.2.21
            connect02.example.internal:
              ansible_host: 192.0.2.22
        monitoring:
          hosts:
            toolbox01.example.internal:
              ansible_host: 192.0.2.31

