---
- name: Recharger systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Redémarrer prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: Redémarrer alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    daemon_reload: true

- name: Redémarrer kafka-exporter
  ansible.builtin.systemd:
    name: kafka-exporter
    state: restarted
    daemon_reload: true

- name: Redémarrer blackbox-exporter
  ansible.builtin.systemd:
    name: blackbox-exporter
    state: restarted
    daemon_reload: true

- name: Redémarrer grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted

- name: Recharger firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true

